# Generated by Django 2.2.2 on 2019-06-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='absentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreman', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100)),
                ('init_date', models.DateTimeField()),
                ('final_date', models.DateTimeField()),
                ('reason', models.CharField(max_length=200)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
