# Generated by Django 2.2.2 on 2019-06-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacationRequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
