# Generated by Django 2.2.2 on 2019-06-19 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacationRequest', '0002_vacationrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacationrequest',
            name='reason',
        ),
    ]
