# Generated by Django 2.2.2 on 2019-06-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacationRequest', '0003_remove_vacationrequest_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='employee',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
