# Generated by Django 2.2.2 on 2019-06-19 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacationRequest', '0004_vacationrequest_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationrequest',
            name='foreman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
