# Generated by Django 2.2.2 on 2019-06-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacationRequest', '0005_auto_20190618_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationrequest',
            name='foreman',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
