# Generated by Django 2.2 on 2019-04-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_Id', models.TextField()),
                ('location', models.TextField()),
                ('drawings_no', models.TextField()),
                ('description', models.TextField()),
                ('date_submitted', models.TextField()),
            ],
        ),
    ]
