# Generated by Django 2.2 on 2019-04-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingsTrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='date_submitted',
            field=models.DateField(),
        ),
    ]
