# Generated by Django 2.2 on 2019-04-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingsTrackerApp', '0002_auto_20190416_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='code_Id',
            field=models.DecimalField(decimal_places=0, max_digits=10000),
        ),
    ]
