# Generated by Django 2.2 on 2019-04-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingsTrackerApp', '0003_auto_20190416_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
