# Generated by Django 2.2 on 2019-04-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingsTrackerApp', '0004_auto_20190416_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='drawings_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
