# Generated by Django 2.2 on 2019-05-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingsTrackerApp', '0005_auto_20190416_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='location',
            field=models.TextField(max_length=100),
        ),
    ]
