# Generated by Django 2.2 on 2019-05-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingsTrackerApp', '0006_auto_20190519_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='date_submitted',
            field=models.TextField(),
        ),
    ]
