# Generated by Django 2.2 on 2019-05-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingsTrackerApp', '0008_auto_20190520_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='code_Id',
            field=models.DecimalField(decimal_places=0, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='date_submitted',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='location',
            field=models.TextField(max_length=100),
        ),
    ]
