# Generated by Django 2.2 on 2019-05-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingsTrackerApp', '0009_auto_20190520_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
