# Generated by Django 2.2 on 2019-05-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingsTrackerApp', '0010_auto_20190520_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='code_Id',
            field=models.CharField(max_length=100),
        ),
    ]
