# Generated by Django 2.2 on 2019-05-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingsTrackerApp', '0011_auto_20190520_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='date_submitted',
            field=models.DateField(),
        ),
    ]
