# Generated by Django 2.2.5 on 2019-10-29 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='file_name',
        ),
    ]
