from django.db import models

class employeeModel(models.Model):

    id               = models.DecimalField(max_length=10)
    employee_name    = models.CharField(max_length=50)
    ibk_number_file  = models.DecimalField(max_length=10)
    cellular         = models.CharField(max_length=15)
    phone            = models.CharField(max_length=15)
    address          = models.CharField(max_length=60)
    zip_code         = models.CharField(max_length=10)
    email            = models.EmailField()
    notes            = models.TextField()
    gender           = models.CharField(max_length=15)
    hire_date        = models.DateField()
    DOB              = models.DateField()
    OSHA_30          = models.BooleanField()
    OSHA_GHS         = models.BooleanField()
    OSHA_GHS_No      = models.CharField(max_length=40)
    FDNY_E_21        = models.BooleanField()
    FDNY_E_21_exp    = models.DateField()
    FDNY_E_21_no     = models.CharField(max_length=50)
    FDNY_F60         = models.BooleanField()
    FDNY_F60_exp     = models.DateField()
    FDNY_F60_no      = models.CharField(max_length=50)
    FDNY_S_93        = models.BooleanField()
    FDNY_S_93_exp    = models.DateField()
    FDNY_S_93_no     = models.CharField(max_length=50)
    FDNY_S_92        = models.BooleanField()
    FDNY_S_92_exp    = models.DateField()
    FDNY_S_92_no     = models.CharField(max_length=50)
    FDNY_A_35        = models.BooleanField()
    FDNY_A_35_exp    = models.DateField()
    FDNY_A_35_no     = models.CharField(max_length=50)
    FDNY_S_92_superviser     = models.BooleanField()
    FDNY_S_92_exp_superviser = models.DateField()
    FDNY_S_92_no_superviser  = models.CharField(max_length=50)
    ACI_ADH_INSTALLER        = models.BooleanField()
    ACI_ADH_INSTALLER_exp    = models.DateField()
    ACI_ADH_INSTALLER_no     = models.CharField(max_length=50)
    ACI_ADH_INSTALLER        = models.BooleanField()
    ACI_ADH_INSTALLER_exp    = models.DateField()
    ACI_ADH_INSTALLER_no     = models.CharField(max_length=50)
    SUPPER_SCAFF_4HR         = models.BooleanField()
    SUPPER_SCAFF_4HR_exp     = models.DateField()
    SUPPER_SCAFF_4HR_no      = models.CharField(max_length=50)
    CSM_30HR                 = models.BooleanField()
    CSM_30HR_exp             = models.DateField()
    CSM_30HR_no              = models.CharField(max_length=50)
    SUPPER_SCAFF_32HR        = models.BooleanField()
    SUPPER_SCAFF_32HR_exp    = models.DateField()
    SUPPER_SCAFF_32HR_no     = models.CharField(max_length=50)
    SUPPER_SCAFF_INSTALLER_AND_REMOVAL = models.BooleanField()




